python_requirements(
    name="reqs",
    source="autoflake_requirements.txt",
)

python_requirements(
    name="reqs0",
    source="black-requirements.txt",
)

python_requirements(
    name="reqs1",
    source="docformatter-requirements.txt",
)

python_requirements(
    name="reqs2",
    source="flake8_requirements.txt",
)

python_requirements(
    name="reqs3",
    source="isort_requirements.txt",
)

python_requirements(
    name="reqs4",
    source="mypy-requirements.txt",
)
