name: "Setup Environment"
description: "Setup Python and Pants"
inputs:
  python-version:
    description: "The Python version to setup"
    required: true
    default: '3.11.*'
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Setup Pants
      run: make setup-pants
      shell: bash
