name: Lint PR title
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
jobs:
  pull-request-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Lint PR title
        run: |
          python ci/lint_pr_title.py "${{ github.event.pull_request.title }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

